// Package nixgen turns .irori.lock.json into a Nix expression. Downloading a jar
// at runtime is fine on an ordinary VPS but wrong on NixOS, so the lock — which
// already holds every URL and checksum — becomes fixed-output derivations that
// the NixOS module feeds back to irori in sealed mode.
package nixgen

import (
	"encoding/base64"
	"encoding/hex"
	"fmt"
	"regexp"
	"sort"
	"strings"

	"github.com/bx-team/irori/internal/config"
	"github.com/bx-team/irori/internal/lock"
)

type Warning struct {
	Target string
	Reason string
}

// Generate renders the expression and any artifacts it had to leave out.
func Generate(cfg *config.Config, lf *lock.File) (string, []Warning) {
	var b strings.Builder
	var warnings []Warning

	b.WriteString("# Generated by `irori nix` from " + config.LockFileName + ". Do not edit.\n")
	b.WriteString("{ fetchurl }:\n\n{\n")
	b.WriteString(fmt.Sprintf("  name = %q;\n", cfg.Server.Name))
	b.WriteString(fmt.Sprintf("  type = %q;\n", string(cfg.Server.Type)))
	b.WriteString(fmt.Sprintf("  mcVersion = %q;\n", cfg.Server.MCVersion))

	b.WriteString("\n  jar = ")
	switch {
	case lf.Core == nil:
		b.WriteString("null; # nothing in the lock yet, run `irori apply` first\n")
		warnings = append(warnings, Warning{"core", "the lock has no core recorded"})
	case !lf.Core.Direct:
		b.WriteString("null;\n")
		warnings = append(warnings, Warning{
			Target: lf.Core.Type + " " + lf.Core.Build,
			Reason: "this core is produced by an installer, not a single download, so it cannot be one fetchurl",
		})
	case lf.Core.URL == "" || lf.Core.SHA256 == "":
		b.WriteString("null;\n")
		warnings = append(warnings, Warning{lf.Core.File, "no URL or checksum in the lock"})
	default:
		b.WriteString(fetchurl(lf.Core.File, lf.Core.URL, "sha256", lf.Core.SHA256, 2))
		b.WriteString(";\n")
	}

	b.WriteString("\n  plugins = {\n")
	addons := append([]lock.Addon(nil), lf.Addons...)
	sort.Slice(addons, func(i, j int) bool { return addons[i].Key < addons[j].Key })
	for _, a := range addons {
		if a.URL == "" {
			warnings = append(warnings, Warning{a.Name, "installed from a local file, nothing to fetch"})
			continue
		}
		algo, sum := "sha512", a.SHA512
		if sum == "" {
			algo, sum = "sha1", a.SHA1
		}
		if sum == "" {
			warnings = append(warnings, Warning{a.Name, "no checksum in the lock"})
			continue
		}
		b.WriteString("    " + attrName(a) + " = ")
		b.WriteString(fetchurl(a.File, a.URL, algo, sum, 4))
		b.WriteString(";\n")
	}
	b.WriteString("  };\n}\n")

	return b.String(), warnings
}

func fetchurl(name, url, algo, hexSum string, indent int) string {
	pad := strings.Repeat(" ", indent)
	return "fetchurl {\n" +
		pad + fmt.Sprintf("  name = %q;\n", name) +
		pad + fmt.Sprintf("  url = %q;\n", url) +
		pad + fmt.Sprintf("  hash = %q;\n", sri(algo, hexSum)) +
		pad + "}"
}

// sri converts the hex digests both APIs return into the base64 SRI form Nix
// wants in `hash`.
func sri(algo, hexSum string) string {
	raw, err := hex.DecodeString(hexSum)
	if err != nil {
		return algo + "-" + hexSum
	}
	return algo + "-" + base64.StdEncoding.EncodeToString(raw)
}

var unsafeAttr = regexp.MustCompile(`[^A-Za-z0-9_-]`)

func attrName(a lock.Addon) string {
	name := a.ID
	if name == "" {
		name = strings.TrimSuffix(a.File, ".jar")
	}
	name = unsafeAttr.ReplaceAllString(name, "-")
	if name == "" || (name[0] >= '0' && name[0] <= '9') {
		name = "_" + name
	}
	return `"` + name + `"`
}
