// nixgen turns .irori.lock.json into a Nix expression
package nixgen

import (
	"encoding/base64"
	"encoding/hex"
	"fmt"
	"regexp"
	"sort"
	"strconv"
	"strings"

	"github.com/bx-team/irori/internal/config"
	"github.com/bx-team/irori/internal/lock"
	"github.com/bx-team/irori/internal/overrides"
	"github.com/bx-team/irori/internal/props"
)

type Warning struct {
	Target string
	Reason string
}

func Generate(cfg *config.Config, lf *lock.File) (string, []Warning) {
	var b strings.Builder
	var warnings []Warning

	b.WriteString("# Generated by `irori nix` from " + config.LockFileName + ". Do not edit.\n")
	b.WriteString("{ fetchurl }:\n\n{\n")
	fmt.Fprintf(&b, "  name = %q;\n", cfg.Server.Name)
	fmt.Fprintf(&b, "  type = %q;\n", string(cfg.Server.Type))
	fmt.Fprintf(&b, "  mcVersion = %q;\n", cfg.Server.MCVersion)

	b.WriteString("\n  jar = ")
	switch {
	case lf.Core == nil:
		b.WriteString("null; # nothing in the lock yet, run `irori apply` first\n")
		warnings = append(warnings, Warning{"core", "the lock has no core recorded"})
	case !lf.Core.Direct:
		b.WriteString("null;\n")
		warnings = append(warnings, Warning{
			Target: lf.Core.Type + " " + lf.Core.Build,
			Reason: "this core is produced by an installer, not a single download, so it cannot be one fetchurl",
		})
	case lf.Core.URL == "" || lf.Core.SHA256 == "":
		b.WriteString("null;\n")
		warnings = append(warnings, Warning{lf.Core.File, "no URL or checksum in the lock"})
	default:
		b.WriteString(fetchurl(lf.Core.File, lf.Core.URL, "sha256", lf.Core.SHA256, 2))
		b.WriteString(";\n")
	}

	b.WriteString("\n  plugins = {\n")
	addons := append([]lock.Addon(nil), lf.Addons...)
	sort.Slice(addons, func(i, j int) bool { return addons[i].Key < addons[j].Key })
	for _, a := range addons {
		if a.URL == "" {
			warnings = append(warnings, Warning{a.Name, "installed from a local file, nothing to fetch"})
			continue
		}
		algo, sum := "sha512", a.SHA512
		if sum == "" {
			algo, sum = "sha1", a.SHA1
		}
		if sum == "" {
			warnings = append(warnings, Warning{a.Name, "no checksum in the lock"})
			continue
		}
		b.WriteString("    " + attrName(a) + " = ")
		b.WriteString(fetchurl(a.File, a.URL, algo, sum, 4))
		b.WriteString(";\n")
	}
	b.WriteString("  };\n")

	b.WriteString("\n  configs = {\n")
	for _, file := range sortedKeys(cfg.Configs) {
		values := cfg.Configs[file]
		fmt.Fprintf(&b, "    %s = {\n", nixString(file))
		for _, key := range sortedKeys(values) {
			if secret(file, key) {
				warnings = append(warnings, Warning{file + " " + key,
					"looks like a secret and everything in /nix/store is world readable"})
			}
			fmt.Fprintf(&b, "      %s = %s;\n", nixString(key), nixValue(values[key]))
		}
		b.WriteString("    };\n")
	}
	b.WriteString("  };\n}\n")

	return b.String(), warnings
}

func sortedKeys[V any](m map[string]V) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

func secret(file, key string) bool {
	if strings.HasSuffix(file, "server.properties") && props.SpecFor(key).Secret {
		return true
	}
	lower := strings.ToLower(key)
	return strings.Contains(lower, "password") || strings.Contains(lower, "secret") ||
		strings.Contains(lower, "token")
}

func nixValue(v any) string {
	switch t := v.(type) {
	case bool:
		if t {
			return "true"
		}
		return "false"
	case float64:
		if t == float64(int64(t)) {
			return strconv.FormatInt(int64(t), 10)
		}
		return strconv.FormatFloat(t, 'f', -1, 64)
	case int:
		return strconv.Itoa(t)
	case nil:
		return `""`
	default:
		return nixString(overrides.Scalar(v))
	}
}

// Nix interpolates ${...} inside a double-quoted string, so a motd that happens
// to contain one has to arrive escaped or the expression will not even parse.
func nixString(s string) string {
	return strings.ReplaceAll(strconv.Quote(s), "${", `\${`)
}

func fetchurl(name, url, algo, hexSum string, indent int) string {
	pad := strings.Repeat(" ", indent)
	return "fetchurl {\n" +
		pad + fmt.Sprintf("  name = %q;\n", name) +
		pad + fmt.Sprintf("  url = %q;\n", url) +
		pad + fmt.Sprintf("  hash = %q;\n", sri(algo, hexSum)) +
		pad + "}"
}

func sri(algo, hexSum string) string {
	raw, err := hex.DecodeString(hexSum)
	if err != nil {
		return algo + "-" + hexSum
	}
	return algo + "-" + base64.StdEncoding.EncodeToString(raw)
}

var unsafeAttr = regexp.MustCompile(`[^A-Za-z0-9_-]`)

func attrName(a lock.Addon) string {
	name := a.ID
	if name == "" {
		name = strings.TrimSuffix(a.File, ".jar")
	}
	name = unsafeAttr.ReplaceAllString(name, "-")
	if name == "" || (name[0] >= '0' && name[0] <= '9') {
		name = "_" + name
	}
	return `"` + name + `"`
}
